### PR TITLE
Google analytics

### PR DESCRIPTION
**Pull request by shahadatalam2020**

### CODE REVIEW

**Comment by gursharan001** [comment]
Hi @shahadatalam2020 , please rebase your fork to the master of this repository and then repoen a PR. I can show you how if you like. Then create a new PR.

**Comment by shahadatalam2020** [comment]
Hi @gursharan001, we rebase our fork to the master of this repository and then we create a new branch. Then create a new PR.

**Comment by shahadatalam2020** [comment]
Hi @gursharan001, we rebase our fork to the master of this repository and then create a new branch.      https://github.com/gursharan001/gskglobalsite/pull/15

**Comment by gursharan001** [comment]
Hi @shahadatalam2020 , GitHub still shows conflicts. I will close this PR. Please open a new one. Thanks.

**Pull request closed without merging**
